database_name="datamatrix"
table_name="monthly_mobile_phone_costs"
data_location="/tmp/datamatrix"
file_name="monthly_mobile_usage.txt"
excel_source="source.xlsx"
csv_source="source.csv"
csv_source_temp="source_temp.csv"
